import React,{useState} from 'react';
import {ActivityIndicator,Alert,Pressable,StyleSheet,Text,TextInput,View} from 'react-native';
import {mockUsers} from '../data/users'; import {useAuth} from '../context/AuthContext'; import {useTheme} from '../context/ThemeContext';
const validEmail=x=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(x); const validPass=x=>/^(?=.*\d).{8,}$/.test(x);
export default function LoginScreen({navigation}){const [mode,setMode]=useState('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[fullName,setFullName]=useState(''),[confirm,setConfirm]=useState(''),[role,setRole]=useState('customer'),[errors,setErrors]=useState({}),[show,setShow]=useState(false),[isSubmitting,setSubmitting]=useState(false);const {login}=useAuth();const {theme}=useTheme();
 const change=(setter,key)=>(v)=>{setter(v);setErrors(e=>({...e,[key]:undefined}))};
 const submit=()=>{let e={};if(!validEmail(email))e.email='Enter a valid email';if(!validPass(password))e.password='Min 8 chars and one digit';if(mode==='signup'){if(!fullName)e.fullName='Required';if(password!==confirm)e.confirm='Passwords do not match'};setErrors(e);if(Object.keys(e).length)return;setSubmitting(true);setTimeout(()=>{const u=mockUsers.find(x=>x.email===email&&x.password===password);if(mode==='login'){if(!u)Alert.alert('Login failed','Invalid mock credentials');else login(u)}else{login({id:'new',fullName,email,password,role})}setSubmitting(false)},1000)};
 const input=(label,val,set,key,secure=false)=><><Text style={[s.label,{color:theme.text}]}>{label}</Text><TextInput value={val} onChangeText={change(set,key)} secureTextEntry={secure&&!show} placeholder={label} placeholderTextColor={theme.muted} style={[s.input,{color:theme.text,borderColor:errors[key]?'#C0392B':theme.border,backgroundColor:theme.card}]}/>{errors[key]&&<Text style={s.err}>{errors[key]}</Text>}</>;
 return <View style={[s.container,{backgroundColor:theme.background}]}><Text style={[s.title,{color:theme.primary}]}>Restaurant App</Text><Text style={[s.subtitle,{color:theme.muted}]}>{mode==='login'?'Welcome back':'Create your account'}</Text>
 {mode==='signup'&&input('Full name',fullName,setFullName,'fullName')}{input('Email',email,setEmail,'email')}{input('Password',password,setPassword,'password',true)}{mode==='signup'&&input('Confirm password',confirm,setConfirm,'confirm',true)}
 {mode==='signup'&&<View style={s.roles}><Pressable onPress={()=>setRole('customer')} style={role==='customer'?s.selected:s.role}><Text>Customer</Text></Pressable><Pressable onPress={()=>setRole('manager')} style={role==='manager'?s.selected:s.role}><Text>Manager</Text></Pressable></View>}
 <Pressable onPress={()=>setShow(v=>!v)}><Text style={{color:theme.primary}}>{show?'Hide password':'Show password'}</Text></Pressable>
 <Pressable disabled={isSubmitting} onPress={submit} style={[s.btn,{backgroundColor:theme.primary}]}>{isSubmitting?<ActivityIndicator color="#fff"/>:<Text style={{color:'#fff',fontWeight:'800'}}>{mode==='login'?'Login':'Sign up'}</Text>}</Pressable>
 <Pressable onPress={()=>{setMode(mode==='login'?'signup':'login');setErrors({})}}><Text style={{color:theme.primary}}>{mode==='login'?'Need an account? Sign up':'Already have an account? Login'}</Text></Pressable>
 </View>}
const s=StyleSheet.create({container:{flex:1,padding:22,justifyContent:'center'},title:{fontSize:34,fontWeight:'900',textAlign:'center'},subtitle:{textAlign:'center',marginBottom:20},label:{fontWeight:'700',marginTop:10},input:{borderWidth:1,borderRadius:10,padding:12,marginTop:5},err:{color:'#C0392B',fontSize:12},btn:{padding:15,borderRadius:10,alignItems:'center',marginVertical:15},roles:{flexDirection:'row',gap:10,marginTop:12},selected:{padding:10,borderWidth:2,borderColor:'#D35400',borderRadius:8},role:{padding:10,borderWidth:1,borderColor:'#aaa',borderRadius:8}});
