import React,{useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {ActivityIndicator,FlatList,Pressable,RefreshControl,StyleSheet,Text,TextInput,View} from 'react-native';
import MenuItemCard from '../components/MenuItemCard'; import {categories,mockMenu} from '../data/menu'; import {useCart} from '../context/CartContext'; import {useTheme} from '../context/ThemeContext'; import useDebounce from '../hooks/useDebounce';
export default function MenuScreen({navigation}){const {theme}=useTheme(),{dispatch}=useCart();const [menuItems,setMenuItems]=useState([]),[selectedCategory,setCategory]=useState('All'),[search,setSearch]=useState(''),[sort,setSort]=useState('default'),[loading,setLoading]=useState(true),[error,setError]=useState(null),[refreshing,setRefreshing]=useState(false),[fav,setFav]=useState([]),[showTop,setShowTop]=useState(false),[history,setHistory]=useState([]);const inputRef=useRef(null),listRef=useRef(null),timerRef=useRef(null),renderRef=useRef(0),prevQuery=useRef('');renderRef.current++;const debounced=useDebounce(search,400);
 useEffect(()=>{let mounted=true;timerRef.current=setTimeout(()=>{if(mounted){setMenuItems(mockMenu);setLoading(false)}},1500);return()=>{clearTimeout(timerRef.current);mounted=false}},[]);
 useEffect(()=>{navigation.setOptions({title:`Menu (${filtered.length})`})},[selectedCategory,debounced,sort,menuItems.length]);
 const filtered=useMemo(()=>{let x=menuItems.filter(i=>(selectedCategory==='All'||i.category===selectedCategory)&&i.name.toLowerCase().includes(debounced.toLowerCase()));if(sort==='low')x.sort((a,b)=>a.price-b.price);if(sort==='high')x.sort((a,b)=>b.price-a.price);if(sort==='name')x.sort((a,b)=>a.name.localeCompare(b.name));return x},[menuItems,selectedCategory,debounced,sort]);
 useEffect(()=>{if(debounced&&debounced!==prevQuery.current){setHistory(h=>[debounced,...h.filter(x=>x!==debounced)].slice(0,5));prevQuery.current=debounced}},[debounced]);
 const onAdd=useCallback(item=>dispatch({type:'ADD_ITEM',item}),[dispatch]);const onFav=useCallback(id=>setFav(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id]),[]);
 const refresh=()=>{setRefreshing(true);setTimeout(()=>{setMenuItems(mockMenu);setRefreshing(false)},700)};
 if(loading)return <View style={s.center}><ActivityIndicator size="large"/><Text style={{color:theme.text}}>Loading menu...</Text></View>;
 return <View style={{flex:1,backgroundColor:theme.background}}><View style={s.search}><Pressable onPress={()=>inputRef.current?.focus()}><Text>🔎</Text></Pressable><TextInput ref={inputRef} value={search} onChangeText={setSearch} placeholder="Search menu..." placeholderTextColor={theme.muted} style={{flex:1,color:theme.text}}/><Pressable onPress={()=>{setSearch('');inputRef.current?.focus()}}><Text>✕</Text></Pressable></View>
 <View style={s.chips}>{categories.map(c=><Pressable key={c} onPress={()=>setCategory(c)} style={[s.chip,selectedCategory===c&&{backgroundColor:theme.primary}]}><Text style={{color:selectedCategory===c?'#fff':theme.text}}>{c}</Text></Pressable>)}</View>
 <View style={s.sort}><Text style={{color:theme.muted}}>Sort:</Text>{[['default','Default'],['low','Price ↑'],['high','Price ↓'],['name','A-Z']].map(([v,l])=><Pressable key={v} onPress={()=>setSort(v)}><Text style={{color:v===sort?theme.primary:theme.text,fontWeight:v===sort?'800':'400'}}>{l}</Text></Pressable>)}</View>
 {search===''&&history.length>0&&<View style={s.history}>{history.map(x=><Pressable key={x} onPress={()=>setSearch(x)}><Text style={{color:theme.primary}}>{x}</Text></Pressable>)}</View>}
 <FlatList ref={listRef} data={filtered} keyExtractor={i=>i.id} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={refresh}/>} onScroll={e=>setShowTop(e.nativeEvent.contentOffset.y>300)} scrollEventThrottle={16} renderItem={({item})=><MenuItemCard item={item} onAdd={onAdd} isFavourite={fav.includes(item.id)} onFavourite={onFav}/>} ListEmptyComponent={<View style={s.center}><Text style={{color:theme.text}}>No menu item matches your search.</Text></View>}/>
 {showTop&&<Pressable onPress={()=>listRef.current?.scrollToOffset({offset:0,animated:true})} style={[s.top,{backgroundColor:theme.primary}]}><Text style={{color:'#fff'}}>↑ Top</Text></Pressable>}
 <Text style={[s.debug,{color:theme.muted}]}>Render count: {renderRef.current}</Text>
 </View>}
const s=StyleSheet.create({center:{flex:1,alignItems:'center',justifyContent:'center'},search:{margin:10,padding:10,borderRadius:12,borderWidth:1,borderColor:'#ccc',flexDirection:'row',gap:8},chips:{flexDirection:'row',paddingHorizontal:8,gap:6},chip:{paddingHorizontal:12,paddingVertical:7,borderRadius:20,borderWidth:1,borderColor:'#ccc'},sort:{flexDirection:'row',justifyContent:'space-around',padding:10},history:{padding:8,gap:5},top:{position:'absolute',right:20,bottom:70,padding:12,borderRadius:24},debug:{position:'absolute',left:8,bottom:8,fontSize:10}});
